{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.secretProvider.keyVaultName | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secretProvider.secretName | quote }}
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.secretProvider.tenantId | quote }}
{{- end }}
