replicaCount: 2
version: blue
image:
  repository: REPLACE_ME_ACR_LOGIN_SERVER/aks-practice-app
  tag: latest
service:
  selectorVersion: blue
secretProvider:
  enabled: true
  workloadIdentityClientId: REPLACE_ME_WORKLOAD_IDENTITY_CLIENT_ID
  tenantId: REPLACE_ME_TENANT_ID
  keyVaultName: REPLACE_ME_KEY_VAULT_NAME
  secretName: tls-cert
ingress:
  enabled: true
  host: prod.example.internal
autoscaling:
  enabled: true
rbac:
  groupObjectId: REPLACE_ME_GROUP_OBJECT_ID
