replicaCount: 2
version: blue
image:
  repository: akspracacru3zgda.azurecr.io/aks-practice-app
  tag: latest
autoscaling:
  enabled: false
service:
  selectorVersion: blue
secretProvider:
  enabled: true
  workloadIdentityClientId: REPLACE_ME_WORKLOAD_IDENTITY_CLIENT_ID
  tenantId: c7d7fabe-6c6d-4fe6-85dc-141d6a150cec
  keyVaultName: aksprackvsuc3yj
  secretName: tls-cert
ingress:
  enabled: true
  host: uat.example.internal
  tlsSecretName: tls-secret
rbac:
  groupObjectId: REPLACE_ME_GROUP_OBJECT_ID
